name: Check & Lint

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: check-and-lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: ${{ matrix.task }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: ["format:check", lint]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up PNPM
        uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
        with:
          cache: true
          runtime: node@lts
      - run: pnpm run ${{ matrix.task }}
